Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  ContainerPort:
    Type: Number
    Default: 8080
Resources:
  Service1v1VirtualNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: demo-mesh-new-name-service1-v1-vn-1
      Spec:
        Listeners:
          - PortMapping:
              Port: 3000
              Protocol: http
        ServiceDiscovery:
          DNS:
            Hostname: service1-v1.dev.demo-mesh-final-cd.local
  Service1v2VirtualNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: demo-mesh-new-name-service1-v2-vn-2
      Spec:
        Listeners:
          - PortMapping:
              Port: 3000
              Protocol: http
        ServiceDiscovery:
          DNS:
            Hostname: service1-v2.dev.demo-mesh-final-cd.local
  Service1VirtualService:
    Type: AWS::AppMesh::VirtualService
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualServiceName: service1-v1.dev-demo-mesh-final-cd.local
      Spec:
        Provider:
          VirtualRouter:
            VirtualRouterName: !GetAtt Service1VirtualRouter.VirtualRouterName
  Service1VirtualRouter:
    Type: AWS::AppMesh::VirtualRouter
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: demo-mesh-new-name-virtual-router
      Spec:
        Listeners:
          - PortMapping:
              Port: !Ref ContainerPort
              Protocol: http
  Service1Route:
    Type: AWS::AppMesh::Route
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: !GetAtt Service1VirtualRouter.VirtualRouterName
      RouteName: demo-mesh-new-name-virtual-route
      Spec:
        HttpRoute:
          Match:
            Prefix: '/'
          Action:
            WeightedTargets:
              - VirtualNode: !GetAtt Service1v1VirtualNode.VirtualNodeName
                Weight: 50
              - VirtualNode: !GetAtt Service1v2VirtualNode.VirtualNodeName
                Weight: 50
Outputs:
  Service1v1VirtualNode:
    Value: !Ref Service1v1VirtualNode
    Export:
      Name: Service1v1VirtualNode # This value can be consumed by a workload manifest or a workload addon.
  Service1v2VirtualNode:
    Value: !Ref Service1v2VirtualNode
    Export:
      Name: Service1v2VirtualNode # This value can be consumed by a workload manifest or a workload addon.
  Service1Route:
    Value: !Ref Service1Route
    Export:
      Name: Service1Route # This value can be consumed by a workload manifest or a workload addon.
  Service1VirtualRouter:
    Value: !Ref Service1VirtualRouter
    Export:
      Name: Service1VirtualRouter # This value can be consumed by a workload manifest or a workload addon.
  Service1VirtualService:
    Value: !Ref Service1VirtualService
    Export:
      Name: Service1VirtualService # This value can be consumed by a workload manifest or a workload addon.
