name: AWS ECS and AppMesh CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env.ENVIRONMENT_NAME
        run: |
          echo "ENVIRONMENT_NAME=dev" >> "$GITHUB_ENV"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup AWS Copilot
        uses: softprops/setup-aws-copilot@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Deploy ECS
        run: |
          ./scripts/update-ecs.sh ${{ secrets.AWS_REGION }}  
      - name: Set branch name
        id: vars
        run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Gitflow
          author_email: nikhil.ramrakhyani@wednesday.is
          message: 'Updated weights, and app.properties.json [skip actions]'
          add: '.'
          push: false

      - name: Git pull origin
        run: |
          git pull origin ${{ github.ref }}

      - name: Pushing to a protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ steps.vars.outputs.stage }}
          unprotect_reviews: true  