name: AWS ECS and AppMesh CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env.ENVIRONMENT_NAME
        run: |
          echo "ENVIRONMENT_NAME=dev" >> "$GITHUB_ENV"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup AWS Copilot
        uses: softprops/setup-aws-copilot@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Deploy ECS
        run: |
          ./scripts/update-ecs.sh ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_REGION }}
  run:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v9
        with:
          message: Updating app.properties and weights
          committer_name: GitHub Actions
          committer_email: actions@github.com