name: AWS ECS and AppMesh CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env.ENVIRONMENT_NAME
        run: |
          echo "ENVIRONMENT_NAME=dev" >> "$GITHUB_ENV"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup AWS Copilot
        uses: softprops/setup-aws-copilot@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Deploy ECS
        run: |
          ./scripts/update-ecs.sh ${{ secrets.AWS_REGION }}
      # - uses: actions/checkout@v2
      # - name: Commit changes
      #   run: |
      #     git config --global user.name 'nikhilleo10'
      #     git config --global user.email 'nikhilleo10@users.noreply.github.com'
      #     git add .
      #     git commit -m "Updated weights and changes in app.properties"
      #     git push    
      - name: Set branch name
        id: vars
        run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Gitflow
          author_email: nikhil.ramrakhyani@wednesday.is
          message: 'Update badges'
          add: '.'
          push: false

      - name: Git pull origin
        run: |
          git pull origin ${{ github.ref }}

      - name: Pushing to a protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ steps.vars.outputs.stage }}
          unprotect_reviews: true  
  # push-on-github:
  #   name: Push on github
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Commit changes
  #       run: |
  #         git config --global user.name 'nikhilleo10'
  #         git config --global user.email 'nikhilleo10@users.noreply.github.com'
  #         git commit -am "Updated weights and changes in app.properties"
  #         git push
  # push-on-protected:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   name: Push to protected branch
  #   steps:
  #   - name: Checkout local repository
  #     uses: actions/checkout@v3

  #   - name: Push to protected branch
  #     uses: CasperWA/push-protected@v2
  #     with:
  #       token: ${{ secrets.PAT }}
  #       branch: main
  #       unprotect_reviews: true

  # push-on-github:
  #   name: Push on github
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   permissions:
  #     # Give the default GITHUB_TOKEN write permission to commit and push the
  #     # added or changed files to the repository.
  #     contents: write

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.PAT }}
  #     # Commit all changed files back to the repository
  #     - uses: stefanzweifel/git-auto-commit-action@v4
